#!/usr/bin/env python3
"""Draws scenarios/two_states/map/provinces.png and provinces.toml (M3-7).

Four provinces on a sea background: the Lowland kingdom's riverlands and coast in
the west, the Highland republic's dale and peaks in the east. Each province is the
region nearest its seed, with wavy borders and a western and southern coastline.

The committed PNG is the source of truth; this script only makes it reproducible.
It uses floating point and the platform's sin/cos, which is fine for drawing a
picture, but a re-run on another machine may move a border by a pixel. Re-commit
the result and the scenario's content hash changes, which is expected.
Standard library only.
"""

import math
import pathlib
import struct
import zlib

W, H = 640, 400
SEA = (40, 70, 110)
# key, colour, seed (also the label anchor)
PROVINCES = [
    ("riverlands", (120, 170, 90), (170, 150)),
    ("coast", (90, 150, 140), (140, 300)),
    ("dale", (170, 140, 90), (420, 240)),
    ("peaks", (150, 150, 165), (500, 110)),
]


def is_sea(x, y):
    west = x < 40 + 18 * math.sin(y / 37)
    south = y > 360 - 0.10 * x + 10 * math.sin(x / 53)
    return west or south


def owner(x, y):
    # Warp the coordinates so borders wave instead of running straight.
    wx, wy = x + 12 * math.sin(y / 23), y + 12 * math.cos(x / 29)
    best = min(range(len(PROVINCES)), key=lambda i: (wx - PROVINCES[i][2][0]) ** 2 + (wy - PROVINCES[i][2][1]) ** 2)
    return PROVINCES[best][1]


def png(width, height, rows):
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)

    raw = b"".join(b"\x00" + bytes(c for px in row for c in px) for row in rows)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)  # 8-bit RGB
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")


def main():
    out = pathlib.Path(__file__).resolve().parent.parent / "scenarios" / "two_states" / "map"
    out.mkdir(parents=True, exist_ok=True)
    rows = [[SEA if is_sea(x, y) else owner(x, y) for x in range(W)] for y in range(H)]
    (out / "provinces.png").write_bytes(png(W, H, rows))
    lines = [
        "# Province map for two_states (M3-7): each province's colour in provinces.png",
        "# and where its name is drawn. Generated by scripts/draw_two_states_map.py.",
        f"background = [{SEA[0]}, {SEA[1]}, {SEA[2]}]  # sea",
    ]
    for key, (r, g, b), (x, y) in PROVINCES:
        lines += ["", "[[province]]", f'key = "{key}"', f"color = [{r}, {g}, {b}]", f"label = [{x}, {y}]"]
    (out / "provinces.toml").write_text("\n".join(lines) + "\n")
    print(f"wrote {out / 'provinces.png'} ({W}x{H}) and provinces.toml")


if __name__ == "__main__":
    main()
