#!/usr/bin/env bash
# Regenerates crates/pax_protocol/src/generated/ from schemas/*.fbs (D22).
#
# The generated code is checked in. CI runs this script and fails if the result
# differs, so the schemas and the code can never drift apart.
#
# flatc must be exactly FLATC_VERSION: generated code only works with the same
# version of the `flatbuffers` runtime crate (pinned in crates/pax_protocol/Cargo.toml).
# On Linux the pinned release is downloaded and checksum-verified into target/tools/.
# Elsewhere, set FLATC to a flatc binary of that version.
set -euo pipefail

FLATC_VERSION=24.3.25
# sha256 of Linux.flatc.binary.g++-13.zip from the v24.3.25 GitHub release.
FLATC_ZIP_SHA256=af4783514309c833216b280914ecc1c993aedb1c2b476f4d499ecbf8c372920e

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/crates/pax_protocol/src/generated"

flatc="${FLATC:-}"
if [ -z "$flatc" ]; then
  dir="$root/target/tools/flatc-$FLATC_VERSION"
  flatc="$dir/flatc"
  if [ ! -x "$flatc" ]; then
    if [ "$(uname -s)" != "Linux" ]; then
      echo "No pinned flatc download for $(uname -s); set FLATC to a flatc $FLATC_VERSION binary." >&2
      exit 1
    fi
    mkdir -p "$dir"
    curl -sSLf -o "$dir/flatc.zip" \
      "https://github.com/google/flatbuffers/releases/download/v$FLATC_VERSION/Linux.flatc.binary.g++-13.zip"
    echo "$FLATC_ZIP_SHA256  $dir/flatc.zip" | sha256sum -c --quiet
    python3 -I -m zipfile -e "$dir/flatc.zip" "$dir"
    chmod +x "$flatc"
  fi
fi

actual="$("$flatc" --version)"
if [ "$actual" != "flatc version $FLATC_VERSION" ]; then
  echo "Need flatc $FLATC_VERSION, but $flatc reports: $actual" >&2
  exit 1
fi

rm -rf "$out"
mkdir -p "$out"
"$flatc" --rust --rust-module-root-file -o "$out" -I "$root/schemas" \
  "$root/schemas/common.fbs" "$root/schemas/client.fbs" "$root/schemas/server.fbs"

# flatc rewrites mod.rs for each input file, so it only registers the last file's
# types. Rebuild it from every generated file, sorted, so the output is deterministic.
# All schemas share the single namespace pax.net.
{
  echo "// Automatically generated by scripts/gen-protocol.sh from flatc output. Do not modify."
  echo "// @generated"
  echo "pub mod pax {"
  echo "  use super::*;"
  echo "  pub mod net {"
  echo "    use super::*;"
  for f in $(cd "$out/pax/net" && ls -- *_generated.rs | LC_ALL=C sort); do
    m="${f%.rs}"
    echo "    mod $m;"
    echo "    pub use self::$m::*;"
  done
  echo "  } // net"
  echo "} // pax"
} > "$out/mod.rs"
if [ "$(find "$out" -name '*_generated.rs' | wc -l)" != "$(grep -c '^    mod ' "$out/mod.rs")" ]; then
  echo "Generated files exist outside pax/net; extend the mod.rs builder for new namespaces." >&2
  exit 1
fi
echo "Generated $(find "$out" -name '*.rs' | wc -l) files in ${out#"$root"/}"
